export const PERMISSIONS = {
  ADMIN: {
    CREATE: 'admin:create',
    READ: 'admin:read',
    UPDATE: 'admin:update',
    DELETE: 'admin:delete',
    RESTORE: 'admin:restore',
  },
  AUDIT_LOG: {
    CREATE: 'audit_log:create',
    READ: 'audit_log:read',
    UPDATE: 'audit_log:update',
    DELETE: 'audit_log:delete',
    RESTORE: 'audit_log:restore',
    ADMIN: 'audit_log:admin',
  },
  BRACKET: {
    CREATE: 'bracket:create',
    READ: 'bracket:read',
    UPDATE: 'bracket:update',
    DELETE: 'bracket:delete',
    RESTORE: 'bracket:restore',
    ADMIN: 'bracket:admin',
  },
  CATALOG: {
    CREATE: 'catalog:create',
    READ: 'catalog:read',
    UPDATE: 'catalog:update',
    DELETE: 'catalog:delete',
    RESTORE: 'catalog:restore',
    ADMIN: 'catalog:admin',
  },
  INVITATION: {
    CREATE: 'invitation:create',
    READ: 'invitation:read',
    UPDATE: 'invitation:update',
    DELETE: 'invitation:delete',
    RESTORE: 'invitation:restore',
    ADMIN: 'invitation:admin',
  },
  LEAGUE: {
    CREATE: 'league:create',
    READ: 'league:read',
    UPDATE: 'league:update',
    DELETE: 'league:delete',
    RESTORE: 'league:restore',
    ADMIN: 'league:admin',
  },
  LEAGUE_REWARD: {
    CREATE: 'league_reward:create',
    READ: 'league_reward:read',
    UPDATE: 'league_reward:update',
    DELETE: 'league_reward:delete',
    RESTORE: 'league_reward:restore',
    ADMIN: 'league_reward:admin',
  },
  MAGIC_LINK: {
    CREATE: 'magic_link:create',
    READ: 'magic_link:read',
    UPDATE: 'magic_link:update',
    DELETE: 'magic_link:delete',
    RESTORE: 'magic_link:restore',
    ADMIN: 'magic_link:admin',
  },
  MATCH: {
    CREATE: 'match:create',
    READ: 'match:read',
    UPDATE: 'match:update',
    DELETE: 'match:delete',
    RESTORE: 'match:restore',
    ADMIN: 'match:admin',
  },
  MATCH_PERIOD: {
    CREATE: 'match_period:create',
    READ: 'match_period:read',
    UPDATE: 'match_period:update',
    DELETE: 'match_period:delete',
    RESTORE: 'match_period:restore',
    ADMIN: 'match_period:admin',
  },
  PERMISSION: {
    CREATE: 'permission:create',
    READ: 'permission:read',
    UPDATE: 'permission:update',
    DELETE: 'permission:delete',
    RESTORE: 'permission:restore',
    ADMIN: 'permission:admin',
  },
  PREDICTION: {
    CREATE: 'prediction:create',
    READ: 'prediction:read',
    UPDATE: 'prediction:update',
    DELETE: 'prediction:delete',
    RESTORE: 'prediction:restore',
    ADMIN: 'prediction:admin',
    READ_ALL: 'prediction:read_all',
  },
  ROLE: {
    CREATE: 'role:create',
    READ: 'role:read',
    UPDATE: 'role:update',
    DELETE: 'role:delete',
    RESTORE: 'role:restore',
    ADMIN: 'role:admin',
  },
  ROLE_PERMISSION: {
    CREATE: 'role_permission:create',
    READ: 'role_permission:read',
    UPDATE: 'role_permission:update',
    DELETE: 'role_permission:delete',
    RESTORE: 'role_permission:restore',
    ADMIN: 'role_permission:admin',
  },
  RULES_LEAGUE: {
    CREATE: 'rules_league:create',
    READ: 'rules_league:read',
    UPDATE: 'rules_league:update',
    DELETE: 'rules_league:delete',
    RESTORE: 'rules_league:restore',
    ADMIN: 'rules_league:admin',
  },
  STADIUM: {
    CREATE: 'stadium:create',
    READ: 'stadium:read',
    UPDATE: 'stadium:update',
    DELETE: 'stadium:delete',
    RESTORE: 'stadium:restore',
    ADMIN: 'stadium:admin',
  },
  SUPPORT: {
    VIEW: 'support:view',
  },
  TEAM: {
    CREATE: 'team:create',
    READ: 'team:read',
    UPDATE: 'team:update',
    DELETE: 'team:delete',
    RESTORE: 'team:restore',
    ADMIN: 'team:admin',
  },
  TEAM_LEAGUE: {
    CREATE: 'team_league:create',
    READ: 'team_league:read',
    UPDATE: 'team_league:update',
    DELETE: 'team_league:delete',
    RESTORE: 'team_league:restore',
  },
  TRANSACTION: {
    CREATE: 'transaction:create',
    READ: 'transaction:read',
    UPDATE: 'transaction:update',
    DELETE: 'transaction:delete',
    RESTORE: 'transaction:restore',
    ADMIN: 'transaction:admin',
  },
  USER: {
    CREATE: 'user:create',
    READ: 'user:read',
    UPDATE: 'user:update',
    DELETE: 'user:delete',
    RESTORE: 'user:restore',
    ADMIN: 'user:admin',
  },
  USER_LEAGUE: {
    CREATE: 'user_league:create',
    READ: 'user_league:read',
    UPDATE: 'user_league:update',
    DELETE: 'user_league:delete',
    RESTORE: 'user_league:restore',
    ADMIN: 'user_league:admin',
  },
  USER_LEAGUE_REWARD: {
    CREATE: 'user_league_reward:create',
    READ: 'user_league_reward:read',
    UPDATE: 'user_league_reward:update',
    DELETE: 'user_league_reward:delete',
    RESTORE: 'user_league_reward:restore',
    ADMIN: 'user_league_reward:admin',
  },
  USER_ROLE: {
    CREATE: 'user_role:create',
    READ: 'user_role:read',
    UPDATE: 'user_role:update',
    DELETE: 'user_role:delete',
    RESTORE: 'user_role:restore',
    ADMIN: 'user_role:admin',
  },
  USER_SESSION: {
    CREATE: 'user_session:create',
    READ: 'user_session:read',
    UPDATE: 'user_session:update',
    DELETE: 'user_session:delete',
    RESTORE: 'user_session:restore',
    ADMIN: 'user_session:admin',
  },
  WALLET: {
    CREATE: 'wallet:create',
    READ: 'wallet:read',
    UPDATE: 'wallet:update',
    DELETE: 'wallet:delete',
    RESTORE: 'wallet:restore',
    ADMIN: 'wallet:admin',
  },
  WORLD_LEAGUE: {
    CREATE: 'world_league:create',
    READ: 'world_league:read',
    UPDATE: 'world_league:update',
    DELETE: 'world_league:delete',
    RESTORE: 'world_league:restore',
    ADMIN: 'world_league:admin',
  },
};
