import { TypeFields } from '../enums/type-fields';
import { FieldBase, FormFields } from '../interfaces/field-props';
import { Validators } from '@angular/forms';

// Mapa de campos usando Record y FieldProps
export const formFields: FormFields = {
  proofForm: {
    fields: [
      {
        icon: 'pi pi-user',
        key: 'nombre', // Identificador único en el objeto de datos
        type: TypeFields.TEXT,
        label: 'Nombre',
        placeholder: 'Tu nombre',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: true, minItems: 1, maxItems: 2 },
        },
        hint: 'Escribe tu nombre completo',
        value: '',
        rules: [Validators.required, Validators.minLength(3), Validators.maxLength(10)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-globe',
        key: 'pais', // Identificador único
        type: TypeFields.SELECT,
        label: 'País',
        placeholder: 'Selecciona un país',
        options: [
          { key: 'ar', value: 'Argentina' },
          { key: 'cl', value: 'Chile' },
          { key: 'mx', value: 'México' },
          { key: 'es', value: 'España' },
        ],
        hint: 'Usa el menú para elegir',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        value: '',
        rules: [Validators.required],
        controlType: TypeFields.SELECT,
        order: 2,
      },
      {
        icon: 'pi pi-globe',
        key: 'numero', // Identificador único
        type: TypeFields.NUMBER,
        label: 'Numero',
        placeholder: 'Ingresa un valor',
        options: [],
        hint: 'Usa el menú para elegir',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        value: 0,
        rules: [Validators.required],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-globe',
        key: 'numero', // Identificador único
        type: TypeFields.CHECKBOX,
        label: 'Checkbox',
        placeholder: 'Ingresa un valor',
        options: [],
        hint: 'Usa el menú para elegir',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        value: 0,
        rules: [Validators.required],
        controlType: TypeFields.CHECKBOX,
        order: 4,
      },
      {
        icon: 'pi pi-globe',
        key: 'numero', // Identificador único
        type: TypeFields.RADIO,
        label: 'Radio',
        placeholder: 'Ingresa un valor',
        options: [
          { key: 'ar', value: 'Argentina' },
          { key: 'cl', value: 'Chile' },
        ],
        hint: 'Usa el menú para elegir',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        value: 0,
        rules: [Validators.required],
        controlType: TypeFields.RADIO,
        order: 5,
      },
      {
        icon: 'pi pi-globe',
        key: 'toggle', // Identificador único
        type: TypeFields.TOGGLE,
        label: 'Toggle',
        placeholder: 'Ingresa un valor',
        options: [],
        hint: 'Usa el menú para elegir',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        value: 0,
        rules: [Validators.required],
        controlType: TypeFields.TOGGLE,
        order: 6,
      },
      {
        icon: 'pi pi-globe',
        key: 'textarea', // Identificador único
        type: TypeFields.TEXTAREA,
        label: 'Área de Texto',
        placeholder: 'Ingresa tu texto aquí...',
        options: [],
        hint: 'Usa el menú para elegir',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        value: 0,
        rules: [Validators.required],
        controlType: TypeFields.TEXTAREA,
        order: 7,
      },
    ],
  },

  stadiumForm: {
    fields: [
      {
        icon: 'pi pi-building',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Nombre del Estadio',
        placeholder: 'Ingresa el nombre del estadio',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Nombre oficial del estadio',
        value: '',
        rules: [Validators.required, Validators.minLength(3)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-globe',
        key: 'catalog_id',
        type: TypeFields.SELECT,
        label: 'ID de Catálogo',
        placeholder: 'Ingresa el ID de catálogo',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'ID del catálogo relacionado al país',
        value: 0,
        rules: [Validators.required],
        options: [],
        optionsSource: {
          table: 'CATALOG',
          filterField: 'table_name',
          filterValue: 'country',
          valueField: 'catalog_id',
          labelField: 'description',
          orderBy: 'description',
          order: 'asc',
          includeDeleted: false,
        },
        controlType: TypeFields.SELECT,
        order: 2,
      },
      {
        icon: 'pi pi-image',
        key: 'logo_url',
        type: TypeFields.IMAGE_UPLOAD,
        label: 'Logo',
        placeholder: '',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 0, maxItems: 1 },
        },
        hint: 'Imagen del estadio (subida a Supabase Storage)',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.IMAGE_UPLOAD,
        storage: { bucket: 'logos', folder: 'stadiums' },
        order: 3,
      },
    ],
  },
  catalogForm: {
    fields: [
      {
        icon: 'pi pi-globe',
        key: 'table_id',
        type: TypeFields.NUMBER,
        label: 'ID de la Tabla',
        placeholder: 'Ingresa el ID de la tabla',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'ID de la tabla en la base de datos',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 0,
      },
      {
        icon: 'pi pi-globe',
        key: 'table_name',
        type: TypeFields.TEXT,
        label: 'Nombre del catalogo',
        placeholder: 'Ingresa el nombre del catalogo',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Nombre del catalogo ',
        value: '',
        rules: [Validators.required, Validators.minLength(3)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-globe',
        key: 'description',
        type: TypeFields.TEXTAREA,
        label: 'Descripción',
        placeholder: 'Ingresa la descripción',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Descripción del catálogo',
        value: '',
        rules: [Validators.required, Validators.minLength(3)],
        options: [],
        controlType: TypeFields.TEXTAREA,
        order: 2,
      },
      {
        icon: 'pi pi-globe',
        key: 'value',
        type: TypeFields.TEXTAREA,
        label: 'Valor',
        placeholder: 'Ingresa el valor',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Valor del catálogo',
        value: '',
        rules: [Validators.required, Validators.minLength(1)],
        options: [],
        controlType: TypeFields.TEXTAREA,
        order: 3,
      },
      {
        icon: 'pi pi-globe',
        key: 'neumonic',
        type: TypeFields.TEXT,
        label: 'Neumónico',
        placeholder: 'Ingresa el neumónico',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Neumónico del catálogo',
        value: '',
        rules: [Validators.required, Validators.maxLength(3)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 4,
      },
    ],
  },
  auditLogForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'new_values',
        type: TypeFields.TEXT,
        label: 'New Values',
        placeholder: 'Ingresa new values',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'New Values',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'old_values',
        type: TypeFields.TEXT,
        label: 'Old Values',
        placeholder: 'Ingresa old values',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Old Values',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'operation_type',
        type: TypeFields.TEXT,
        label: 'Operation Type',
        placeholder: 'Ingresa operation type',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Operation Type',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'table_name',
        type: TypeFields.TEXT,
        label: 'Table Name',
        placeholder: 'Ingresa table name',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Table Name',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 4,
      },
    ],
  },
  invitationForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'expiration_date',
        type: TypeFields.DATE,
        label: 'Expiration Date',
        placeholder: 'Ingresa expiration date',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Expiration Date',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.DATE,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'send_date',
        type: TypeFields.DATE,
        label: 'Send Date',
        placeholder: 'Ingresa send date',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Send Date',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.DATE,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'status',
        type: TypeFields.TEXT,
        label: 'Status',
        placeholder: 'Ingresa status',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Status',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'token',
        type: TypeFields.TEXT,
        label: 'Token',
        placeholder: 'Ingresa token',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Token',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 4,
      },
      {
        icon: 'pi pi-database',
        key: 'user_league_id',
        type: TypeFields.NUMBER,
        label: 'User League Id',
        placeholder: 'Ingresa user league id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User League Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 5,
      },
    ],
  },

  leagueRewardForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'global_prize_1pct',
        type: TypeFields.NUMBER,
        label: 'Global Prize 1pct',
        placeholder: 'Ingresa global prize 1pct',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Global Prize 1pct',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'league_id',
        type: TypeFields.NUMBER,
        label: 'League Id',
        placeholder: 'Ingresa league id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'League Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'platform_fee_5pct',
        type: TypeFields.NUMBER,
        label: 'Platform Fee 5pct',
        placeholder: 'Ingresa platform fee 5pct',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Platform Fee 5pct',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'total_collected_amount',
        type: TypeFields.NUMBER,
        label: 'Total Collected Amount',
        placeholder: 'Ingresa total collected amount',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Total Collected Amount',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 4,
      },
    ],
  },
  matchForm: {
    fields: [
      {
        icon: 'pi pi-tag',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Nombre del partido',
        placeholder: 'Ej. México vs Argentina',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Nombre descriptivo del partido',
        value: '',
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'first_team_total',
        type: TypeFields.NUMBER,
        label: 'First Team Total',
        placeholder: 'Ingresa first team total',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'First Team Total',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'league_id',
        type: TypeFields.NUMBER,
        label: 'League Id',
        placeholder: 'Ingresa league id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'League Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'match_id',
        type: TypeFields.NUMBER,
        label: 'Match Id',
        placeholder: 'Ingresa match id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Match Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 4,
      },
      {
        icon: 'pi pi-database',
        key: 'second_team_total',
        type: TypeFields.NUMBER,
        label: 'Second Team Total',
        placeholder: 'Ingresa second team total',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Second Team Total',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 5,
      },
      {
        icon: 'pi pi-database',
        key: 'stadium_id',
        type: TypeFields.NUMBER,
        label: 'Stadium Id',
        placeholder: 'Ingresa stadium id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Stadium Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 6,
      },
      {
        icon: 'pi pi-database',
        key: 'start_time',
        type: TypeFields.DATE,
        label: 'Start Time',
        placeholder: 'Ingresa start time',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Start Time',
        value: '',
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.DATE,
        order: 7,
      },
      {
        icon: 'pi pi-calendar-times',
        key: 'end_time',
        type: TypeFields.DATE,
        label: 'Fecha fin del partido',
        placeholder: '',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 0, maxItems: 1 },
        },
        hint: 'Fecha y hora en que termina el partido',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.DATE,
        order: 8,
      },
    ],
  },
  matchPeriodForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'catalog_id',
        type: TypeFields.SELECT,
        label: 'Tipo de período',
        placeholder: 'Selecciona el período',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Período del partido (1T, 2T, Penales…)',
        value: 0,
        rules: [Validators.required],
        options: [],
        optionsSource: {
          table: 'CATALOG',
          valueField: 'catalog_id',
          filterField: 'table_id',
          filterValue: 30,
          labelField: 'description',
          orderBy: 'description',
          order: 'asc',
          includeDeleted: false,
        },
        controlType: TypeFields.SELECT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'first_team_score',
        type: TypeFields.NUMBER,
        label: 'First Team Score',
        placeholder: 'Ingresa first team score',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'First Team Score',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'match_id',
        type: TypeFields.NUMBER,
        label: 'Match Id',
        placeholder: 'Ingresa match id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Match Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'second_team_score',
        type: TypeFields.NUMBER,
        label: 'Second Team Score',
        placeholder: 'Ingresa second team score',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Second Team Score',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 4,
      },
    ],
  },
  permissionForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'description',
        type: TypeFields.TEXT,
        label: 'Description',
        placeholder: 'Ingresa description',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Description',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Name',
        placeholder: 'Ingresa name',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Name',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'permission_id',
        type: TypeFields.NUMBER,
        label: 'Permission Id',
        placeholder: 'Ingresa permission id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Permission Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
    ],
  },
  predictionForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'first_team_score',
        type: TypeFields.NUMBER,
        label: 'First Team Score',
        placeholder: 'Ingresa first team score',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'First Team Score',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'match_id',
        type: TypeFields.SELECT,
        label: 'Match Id',
        placeholder: 'Ingresa match id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Match Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        optionsSource: {
          table: 'MATCH',
          valueField: 'match_id',
          filterField: 'match_id',
          labelField: 'name',
          orderBy: 'name',
          order: 'asc',
          includeDeleted: false,
        },
        controlType: TypeFields.SELECT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'second_team_score',
        type: TypeFields.NUMBER,
        label: 'Second Team Score',
        placeholder: 'Ingresa second team score',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Second Team Score',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'turn',
        type: TypeFields.SELECT,
        label: 'Turn',
        placeholder: 'Ingresa turn',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        optionsSource: {
          table: 'MATCH_PERIOD',
          valueField: 'turn',
          filterField: 'match_id',
          labelField: 'period_id',
          orderBy: 'period_id',
          order: 'desc',
          includeDeleted: false,
        },
        hint: 'Turn',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.SELECT,
        order: 4,
      },
      {
        icon: 'pi pi-database',
        key: 'user_league_id',
        type: TypeFields.SELECT,
        label: 'User League Id',
        placeholder: 'Ingresa user league id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        optionsSource: {
          table: 'USER_LEAGUE',
          valueField: 'user_league_id',
          filterField: 'user_league_id',
          labelField: 'name',
          orderBy: 'name',
          order: 'asc',
          includeDeleted: false,
        },
        hint: 'User League Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.SELECT,
        order: 5,
      },
    ],
  },
  roleForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'description',
        type: TypeFields.TEXT,
        label: 'Description',
        placeholder: 'Ingresa description',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Description',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Name',
        placeholder: 'Ingresa name',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Name',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
    ],
  },
  rolePermissionForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'permission_id',
        type: TypeFields.SELECT,
        label: 'Permission Id',
        placeholder: 'Ingresa permission id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        optionsSource: {
          table: 'PERMISSION',
          valueField: 'permission_id',
          filterField: 'permission_id',
          labelField: 'name',
          orderBy: 'name',
          order: 'asc',
          includeDeleted: false,
        },
        hint: 'Permission Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.SELECT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'role_id',
        type: TypeFields.SELECT,
        label: 'Role Id',
        placeholder: 'Ingresa role id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        optionsSource: {
          table: 'ROLE',
          valueField: 'role_id',
          filterField: 'role_id',
          labelField: 'name',
          orderBy: 'name',
          order: 'asc',
          includeDeleted: false,
        },
        hint: 'Role Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.SELECT,
        order: 2,
      },
    ],
  },
  rulesLeagueForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'description',
        type: TypeFields.TEXT,
        label: 'Description',
        placeholder: 'Ingresa description',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Description',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'dimension',
        type: TypeFields.TEXT,
        label: 'Dimension',
        placeholder: 'Ingresa dimension',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Dimension',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'league_id',
        type: TypeFields.NUMBER,
        label: 'League Id',
        placeholder: 'Ingresa league id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'League Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'value',
        type: TypeFields.TEXT,
        label: 'Value',
        placeholder: 'Ingresa value',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Value',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 4,
      },
    ],
  },
  transactionForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'amount',
        type: TypeFields.NUMBER,
        label: 'Amount',
        placeholder: 'Ingresa amount',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Amount',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'catalog_id',
        type: TypeFields.SELECT,
        label: 'Tipo de transacción',
        placeholder: 'Selecciona el tipo',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Depósito, retiro, premio, etc.',
        value: 0,
        rules: [Validators.required],
        options: [],
        optionsSource: {
          table: 'CATALOG',
          valueField: 'catalog_id',
          filterField: 'table_id',
          filterValue: 40,
          labelField: 'description',
          orderBy: 'description',
          order: 'asc',
          includeDeleted: false,
        },
        controlType: TypeFields.SELECT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'description',
        type: TypeFields.TEXT,
        label: 'Description',
        placeholder: 'Ingresa description',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Description',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'transaction_date',
        type: TypeFields.DATE,
        label: 'Transaction Date',
        placeholder: 'Ingresa transaction date',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Transaction Date',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.DATE,
        order: 4,
      },
      {
        icon: 'pi pi-database',
        key: 'wallet_id',
        type: TypeFields.NUMBER,
        label: 'Wallet Id',
        placeholder: 'Ingresa wallet id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Wallet Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 5,
      },
    ],
  },
  userForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'email',
        type: TypeFields.EMAIL,
        label: 'Email',
        placeholder: 'Ingresa email',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Email',
        value: '',
        rules: [Validators.required, Validators.email],
        options: [],
        controlType: TypeFields.EMAIL,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'login',
        type: TypeFields.TEXT,
        label: 'Login',
        placeholder: 'Ingresa login',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Login',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Name',
        placeholder: 'Ingresa name',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Name',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'password_hash',
        type: TypeFields.PASSWORD,
        label: 'Password Hash',
        placeholder: 'Ingresa password hash',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Password Hash',
        value: '',
        rules: [Validators.required, Validators.minLength(6)],
        options: [],
        controlType: TypeFields.PASSWORD,
        order: 4,
      },
      {
        icon: 'pi pi-database',
        key: 'registration_date',
        type: TypeFields.DATE,
        label: 'Registration Date',
        placeholder: 'Ingresa registration date',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Registration Date',
        value: '',
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.DATE,
        order: 5,
      },
      {
        icon: 'pi pi-database',
        key: 'status',
        type: TypeFields.TEXT,
        label: 'Status',
        placeholder: 'Ingresa status',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Status',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 6,
      },
      {
        icon: 'pi pi-database',
        key: 'user_id',
        type: TypeFields.NUMBER,
        label: 'User Id',
        placeholder: 'Ingresa user id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 7,
      },
    ],
  },
  userLeagueForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'accumulated_points',
        type: TypeFields.NUMBER,
        label: 'Accumulated Points',
        placeholder: 'Ingresa accumulated points',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Accumulated Points',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'league_id',
        type: TypeFields.NUMBER,
        label: 'League Id',
        placeholder: 'Ingresa league id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'League Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'user_id',
        type: TypeFields.SELECT,
        label: 'User Id',
        placeholder: 'Ingresa user id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        optionsSource: {
          table: 'USER',
          valueField: 'user_id',
          filterField: 'user_id',
          labelField: 'name',
          orderBy: 'name',
          order: 'asc',
          includeDeleted: false,
        },
        hint: 'User Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
    ],
  },
  userLeagueRewardForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'amount',
        type: TypeFields.NUMBER,
        label: 'Amount',
        placeholder: 'Ingresa amount',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Amount',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'payment_date',
        type: TypeFields.DATE,
        label: 'Payment Date',
        placeholder: 'Ingresa payment date',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Payment Date',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.DATE,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'status',
        type: TypeFields.TEXT,
        label: 'Status',
        placeholder: 'Ingresa status',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Status',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'user_league_id',
        type: TypeFields.NUMBER,
        label: 'User League Id',
        placeholder: 'Ingresa user league id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User League Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 4,
      },
    ],
  },
  userRoleForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'role_id',
        type: TypeFields.SELECT,
        label: 'Role Id',
        placeholder: 'Ingresa role id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        optionsSource: {
          table: 'ROLE',
          valueField: 'role_id',
          filterField: 'role_id',
          labelField: 'name',
          orderBy: 'name',
          order: 'asc',
          includeDeleted: false,
        },
        hint: 'Role Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.SELECT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'user_id',
        type: TypeFields.SELECT,
        label: 'User Id',
        placeholder: 'Ingresa user id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.SELECT,
        order: 2,
        optionsSource: {
          table: 'USER',
          valueField: 'user_id',
          filterField: 'user_id',
          labelField: 'name',
          orderBy: 'name',
          order: 'asc',
          includeDeleted: false,
        },
      },
    ],
  },
  userSessionForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'ip_address',
        type: TypeFields.TEXT,
        label: 'Ip Address',
        placeholder: 'Ingresa ip address',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Ip Address',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'login',
        type: TypeFields.TEXT,
        label: 'Login',
        placeholder: 'Ingresa login',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Login',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'sign_in',
        type: TypeFields.TEXT,
        label: 'Sign In',
        placeholder: 'Ingresa sign in',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Sign In',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'sign_out',
        type: TypeFields.TEXT,
        label: 'Sign Out',
        placeholder: 'Ingresa sign out',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Sign Out',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 4,
      },
      {
        icon: 'pi pi-database',
        key: 'user_agent',
        type: TypeFields.TEXT,
        label: 'User Agent',
        placeholder: 'Ingresa user agent',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User Agent',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 5,
      },
      {
        icon: 'pi pi-database',
        key: 'user_id',
        type: TypeFields.NUMBER,
        label: 'User Id',
        placeholder: 'Ingresa user id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 6,
      },
    ],
  },
  walletForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'balance',
        type: TypeFields.NUMBER,
        label: 'Balance',
        placeholder: 'Ingresa balance',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Balance',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'status',
        type: TypeFields.TEXT,
        label: 'Status',
        placeholder: 'Ingresa status',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Status',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'user_id',
        type: TypeFields.NUMBER,
        label: 'User Id',
        placeholder: 'Ingresa user id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'wallet_id',
        type: TypeFields.NUMBER,
        label: 'Wallet Id',
        placeholder: 'Ingresa wallet id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Wallet Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 4,
      },
    ],
  },
  predictionClientForm: {
    fields: [
      {
        icon: 'pi pi-shield',
        key: 'first_team_score',
        type: TypeFields.NUMBER,
        label: 'Goles Local',
        placeholder: '0',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Goles que predices para el equipo local',
        value: 0,
        rules: [Validators.required, Validators.min(0)],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-shield',
        key: 'second_team_score',
        type: TypeFields.NUMBER,
        label: 'Goles Visitante',
        placeholder: '0',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Goles que predices para el equipo visitante',
        value: 0,
        rules: [Validators.required, Validators.min(0)],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
      {
        icon: 'pi pi-wallet',
        key: 'wager_amount',
        type: TypeFields.NUMBER,
        label: 'Apuesta (MXN)',
        placeholder: '0',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Cantidad que deseas apostar en este partido',
        value: 0,
        rules: [Validators.min(0)],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
    ],
  },
  worldLeagueForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Name',
        placeholder: 'Ingresa name',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Name',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'world_league_id',
        type: TypeFields.NUMBER,
        label: 'World League Id',
        placeholder: 'Ingresa world league id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'World League Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
      {
        icon: 'pi pi-image',
        key: 'logo_url',
        type: TypeFields.IMAGE_UPLOAD,
        label: 'Logo',
        placeholder: '',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 0, maxItems: 1 },
        },
        hint: 'Imagen de la liga mundial (subida a Supabase Storage)',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.IMAGE_UPLOAD,
        storage: { bucket: 'logos', folder: 'world-leagues' },
        order: 3,
      },
    ],
  },
  loginForm: {
    fields: [
      {
        icon: 'pi pi-user',
        key: 'email',
        type: TypeFields.EMAIL,
        label: 'Correo Electrónico',
        placeholder: 'Ingresa tu correo electrónico',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Correo electrónico para iniciar sesión',
        value: '',
        rules: [Validators.required, Validators.email],
        options: [],
        controlType: TypeFields.EMAIL,
        order: 1,
      },
      {
        icon: 'pi pi-lock',
        key: 'password',
        type: TypeFields.PASSWORD,
        label: 'Contraseña',
        placeholder: 'Ingresa tu contraseña',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Contraseña para iniciar sesión',
        value: '',
        rules: [Validators.required, Validators.minLength(6)],
        options: [],
        controlType: TypeFields.PASSWORD,
        order: 2,
      },
    ],
  },
  registerForm: {
    fields: [
      {
        icon: 'pi pi-user',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Nombre completo',
        placeholder: 'Ingresa tu nombre',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Como quieres que te llamen en la plataforma',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-envelope',
        key: 'email',
        type: TypeFields.EMAIL,
        label: 'Correo Electrónico',
        placeholder: 'Ingresa tu correo electrónico',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Se usará para validar tu cuenta',
        value: '',
        rules: [Validators.required, Validators.email],
        options: [],
        controlType: TypeFields.EMAIL,
        order: 2,
      },
      {
        icon: 'pi pi-lock',
        key: 'password',
        type: TypeFields.PASSWORD,
        label: 'Contraseña',
        placeholder: 'Crea tu contraseña',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Mínimo 6 caracteres',
        value: '',
        rules: [Validators.required, Validators.minLength(6)],
        options: [],
        controlType: TypeFields.PASSWORD,
        order: 3,
      },
      {
        icon: 'pi pi-lock',
        key: 'confirmPassword',
        type: TypeFields.PASSWORD,
        label: 'Confirmar contraseña',
        placeholder: 'Repite tu contraseña',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Debe coincidir con la contraseña anterior',
        value: '',
        rules: [Validators.required, Validators.minLength(6)],
        options: [],
        controlType: TypeFields.PASSWORD,
        order: 4,
      },
    ],
  },
  changePasswordForm: {
    fields: [
      {
        icon: 'pi pi-envelope',
        key: 'email',
        type: TypeFields.EMAIL,
        label: 'Correo Electrónico',
        placeholder: 'Ingresa tu correo electrónico',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Te enviaremos un enlace para restablecer tu contraseña',
        value: '',
        rules: [Validators.required, Validators.email],
        options: [],
        controlType: TypeFields.EMAIL,
        order: 1,
      },
    ],
  },
  updatePasswordForm: {
    fields: [
      {
        icon: 'pi pi-lock',
        key: 'newPassword',
        type: TypeFields.PASSWORD,
        label: 'Nueva Contraseña',
        placeholder: 'Ingresa tu nueva contraseña',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Debe tener al menos 6 caracteres',
        value: '',
        rules: [Validators.required, Validators.minLength(6)],
        options: [],
        controlType: TypeFields.PASSWORD,
        order: 1,
      },
    ],
  },
  teamLeagueForm: {
    fields: [
      {
        icon: 'pi pi-shield',
        key: 'league_id',
        type: TypeFields.SELECT,
        label: 'Liga',
        placeholder: 'Selecciona una liga',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        optionsSource: {
          table: 'LEAGUE',
          valueField: 'league_id',
          filterField: 'league_id',
          labelField: 'name',
          orderBy: 'name',
          order: 'asc',
          includeDeleted: false,
        },
        hint: 'Liga a la que pertenece el equipo',
        value: null,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-users',
        key: 'team_id',
        type: TypeFields.SELECT,
        label: 'Equipo',
        placeholder: 'Selecciona un equipo',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        optionsSource: {
          table: 'TEAM',
          valueField: 'team_id',
          filterField: 'team_id',
          labelField: 'name',
          orderBy: 'name',
          order: 'asc',
          includeDeleted: false,
        },
        hint: 'Equipo que participa en la liga',
        value: null,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
      {
        icon: 'pi pi-star',
        key: 'points',
        type: TypeFields.INTEGER,
        label: 'Puntos',
        placeholder: '0',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Puntos acumulados en la liga',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.INTEGER,
        order: 3,
      },
      {
        icon: 'pi pi-calendar',
        key: 'games_played',
        type: TypeFields.INTEGER,
        label: 'Partidos Jugados',
        placeholder: '0',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Total de partidos disputados',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.INTEGER,
        order: 4,
      },
      {
        icon: 'pi pi-check-circle',
        key: 'wins',
        type: TypeFields.INTEGER,
        label: 'Victorias',
        placeholder: '0',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Partidos ganados',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.INTEGER,
        order: 5,
      },
      {
        icon: 'pi pi-minus-circle',
        key: 'draws',
        type: TypeFields.INTEGER,
        label: 'Empates',
        placeholder: '0',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Partidos empatados',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.INTEGER,
        order: 6,
      },
      {
        icon: 'pi pi-times-circle',
        key: 'losses',
        type: TypeFields.INTEGER,
        label: 'Derrotas',
        placeholder: '0',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Partidos perdidos',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.INTEGER,
        order: 7,
      },
      {
        icon: 'pi pi-arrow-up',
        key: 'goals_for',
        type: TypeFields.INTEGER,
        label: 'Goles a Favor',
        placeholder: '0',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Goles marcados por el equipo',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.INTEGER,
        order: 8,
      },
      {
        icon: 'pi pi-arrow-down',
        key: 'goals_against',
        type: TypeFields.INTEGER,
        label: 'Goles en Contra',
        placeholder: '0',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Goles recibidos por el equipo',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.INTEGER,
        order: 9,
      },
    ],
  },
};
