import { TypeFields } from '../enums/type-fields';
import { FieldBase } from '../interfaces/field-props';
import { Validators } from '@angular/forms';

// Mapa de campos usando Record y FieldProps
export const formFields: Record<string, { fields: FieldBase<any>[] }> = {
  proofForm: {
    fields: [
      {
        icon: 'pi pi-user',
        key: 'nombre', // Identificador único en el objeto de datos
        type: TypeFields.TEXT,
        label: 'Nombre',
        placeholder: 'Tu nombre',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: true, minItems: 1, maxItems: 2 },
        },
        hint: 'Escribe tu nombre completo',
        value: '',
        rules: [Validators.required, Validators.minLength(3), Validators.maxLength(10)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-globe',
        key: 'pais', // Identificador único
        type: TypeFields.SELECT,
        label: 'País',
        placeholder: 'Selecciona un país',
        options: [
          { key: 'ar', value: 'Argentina' },
          { key: 'cl', value: 'Chile' },
          { key: 'mx', value: 'México' },
          { key: 'es', value: 'España' },
        ],
        hint: 'Usa el menú para elegir',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        value: '',
        rules: [Validators.required],
        controlType: TypeFields.SELECT,
        order: 2,
      },
      {
        icon: 'pi pi-globe',
        key: 'numero', // Identificador único
        type: TypeFields.NUMBER,
        label: 'Numero',
        placeholder: 'Ingresa un valor',
        options: [],
        hint: 'Usa el menú para elegir',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        value: 0,
        rules: [Validators.required],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-globe',
        key: 'numero', // Identificador único
        type: TypeFields.CHECKBOX,
        label: 'Checkbox',
        placeholder: 'Ingresa un valor',
        options: [],
        hint: 'Usa el menú para elegir',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        value: 0,
        rules: [Validators.required],
        controlType: TypeFields.CHECKBOX,
        order: 4,
      },
      {
        icon: 'pi pi-globe',
        key: 'numero', // Identificador único
        type: TypeFields.RADIO,
        label: 'Radio',
        placeholder: 'Ingresa un valor',
        options: [
          { key: 'ar', value: 'Argentina' },
          { key: 'cl', value: 'Chile' },
        ],
        hint: 'Usa el menú para elegir',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        value: 0,
        rules: [Validators.required],
        controlType: TypeFields.RADIO,
        order: 5,
      },
      {
        icon: 'pi pi-globe',
        key: 'toggle', // Identificador único
        type: TypeFields.TOGGLE,
        label: 'Toggle',
        placeholder: 'Ingresa un valor',
        options: [],
        hint: 'Usa el menú para elegir',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        value: 0,
        rules: [Validators.required],
        controlType: TypeFields.TOGGLE,
        order: 6,
      },
      {
        icon: 'pi pi-globe',
        key: 'textarea', // Identificador único
        type: TypeFields.TEXTAREA,
        label: 'Área de Texto',
        placeholder: 'Ingresa tu texto aquí...',
        options: [],
        hint: 'Usa el menú para elegir',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        value: 0,
        rules: [Validators.required],
        controlType: TypeFields.TEXTAREA,
        order: 7,
      },
    ],
  },
  teamForm: {
    fields: [
      {
        icon: 'pi pi-users',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Nombre del Equipo',
        placeholder: 'Ingresa el nombre del equipo',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Nombre oficial del equipo',
        value: '',
        rules: [Validators.required, Validators.minLength(3)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-globe',
        key: 'catalog_id',
        type: TypeFields.NUMBER,
        label: 'ID de Catálogo',
        placeholder: 'Ingresa el ID de catálogo',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'ID del catálogo de países',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
    ],
  },
  stadiumForm: {
    fields: [
      {
        icon: 'pi pi-building',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Nombre del Estadio',
        placeholder: 'Ingresa el nombre del estadio',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Nombre oficial del estadio',
        value: '',
        rules: [Validators.required, Validators.minLength(3)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-globe',
        key: 'catalog_id',
        type: TypeFields.NUMBER,
        label: 'ID de Catálogo',
        placeholder: 'Ingresa el ID de catálogo',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'ID del catálogo relacionado al país',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
    ],
  },
  catalogForm: {
    fields: [
      {
        icon: 'pi pi-globe',
        key: 'table_id',
        type: TypeFields.NUMBER,
        label: 'ID de la Tabla',
        placeholder: 'Ingresa el ID de la tabla',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'ID de la tabla en la base de datos',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 0,
      },
      {
        icon: 'pi pi-globe',
        key: 'table_name',
        type: TypeFields.TEXT,
        label: 'Nombre de la Tabla',
        placeholder: 'Ingresa el nombre de la tabla',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Nombre de la tabla en la base de datos',
        value: '',
        rules: [Validators.required, Validators.minLength(3)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-globe',
        key: 'description',
        type: TypeFields.TEXTAREA,
        label: 'Descripción',
        placeholder: 'Ingresa la descripción',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Descripción del catálogo',
        value: '',
        rules: [Validators.required, Validators.minLength(3)],
        options: [],
        controlType: TypeFields.TEXTAREA,
        order: 2,
      },
      {
        icon: 'pi pi-globe',
        key: 'value',
        type: TypeFields.TEXTAREA,
        label: 'Valor',
        placeholder: 'Ingresa el valor',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Valor del catálogo',
        value: '',
        rules: [Validators.required, Validators.minLength(3)],
        options: [],
        controlType: TypeFields.TEXTAREA,
        order: 3,
      },
      {
        icon: 'pi pi-globe',
        key: 'neumonic',
        type: TypeFields.TEXT,
        label: 'Neumónico',
        placeholder: 'Ingresa el neumónico',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Neumónico del catálogo',
        value: '',
        rules: [Validators.required, Validators.maxLength(3)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 4,
      },
    ],
  },
  auditLogForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'new_values',
        type: TypeFields.TEXT,
        label: 'New Values',
        placeholder: 'Ingresa new values',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'New Values',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'old_values',
        type: TypeFields.TEXT,
        label: 'Old Values',
        placeholder: 'Ingresa old values',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Old Values',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'operation_type',
        type: TypeFields.TEXT,
        label: 'Operation Type',
        placeholder: 'Ingresa operation type',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Operation Type',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'table_name',
        type: TypeFields.TEXT,
        label: 'Table Name',
        placeholder: 'Ingresa table name',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Table Name',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 4,
      },
    ],
  },
  invitationForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'expiration_date',
        type: TypeFields.DATE,
        label: 'Expiration Date',
        placeholder: 'Ingresa expiration date',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Expiration Date',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.DATE,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'send_date',
        type: TypeFields.DATE,
        label: 'Send Date',
        placeholder: 'Ingresa send date',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Send Date',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.DATE,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'status',
        type: TypeFields.TEXT,
        label: 'Status',
        placeholder: 'Ingresa status',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Status',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'token',
        type: TypeFields.TEXT,
        label: 'Token',
        placeholder: 'Ingresa token',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Token',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 4,
      },
      {
        icon: 'pi pi-database',
        key: 'user_league_id',
        type: TypeFields.NUMBER,
        label: 'User League Id',
        placeholder: 'Ingresa user league id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User League Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 5,
      },
    ],
  },
  leagueForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'catalog_id',
        type: TypeFields.NUMBER,
        label: 'Catalog Id',
        placeholder: 'Ingresa catalog id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Catalog Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'invitation_code',
        type: TypeFields.TEXT,
        label: 'Invitation Code',
        placeholder: 'Ingresa invitation code',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Invitation Code',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'league_id',
        type: TypeFields.NUMBER,
        label: 'League Id',
        placeholder: 'Ingresa league id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'League Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Name',
        placeholder: 'Ingresa name',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Name',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 4,
      },
      {
        icon: 'pi pi-database',
        key: 'status',
        type: TypeFields.TEXT,
        label: 'Status',
        placeholder: 'Ingresa status',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Status',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 5,
      },
      {
        icon: 'pi pi-database',
        key: 'user_id',
        type: TypeFields.NUMBER,
        label: 'User Id',
        placeholder: 'Ingresa user id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 6,
      },
      {
        icon: 'pi pi-database',
        key: 'world_league_id',
        type: TypeFields.NUMBER,
        label: 'World League Id',
        placeholder: 'Ingresa world league id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'World League Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 7,
      },
    ],
  },
  leagueRewardForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'global_prize_1pct',
        type: TypeFields.NUMBER,
        label: 'Global Prize 1pct',
        placeholder: 'Ingresa global prize 1pct',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Global Prize 1pct',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'league_id',
        type: TypeFields.NUMBER,
        label: 'League Id',
        placeholder: 'Ingresa league id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'League Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'platform_fee_5pct',
        type: TypeFields.NUMBER,
        label: 'Platform Fee 5pct',
        placeholder: 'Ingresa platform fee 5pct',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Platform Fee 5pct',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'total_collected_amount',
        type: TypeFields.NUMBER,
        label: 'Total Collected Amount',
        placeholder: 'Ingresa total collected amount',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Total Collected Amount',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 4,
      },
    ],
  },
  matchForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'first_team_total',
        type: TypeFields.NUMBER,
        label: 'First Team Total',
        placeholder: 'Ingresa first team total',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'First Team Total',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'league_id',
        type: TypeFields.NUMBER,
        label: 'League Id',
        placeholder: 'Ingresa league id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'League Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'match_id',
        type: TypeFields.NUMBER,
        label: 'Match Id',
        placeholder: 'Ingresa match id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Match Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'second_team_total',
        type: TypeFields.NUMBER,
        label: 'Second Team Total',
        placeholder: 'Ingresa second team total',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Second Team Total',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 4,
      },
      {
        icon: 'pi pi-database',
        key: 'stadium_id',
        type: TypeFields.NUMBER,
        label: 'Stadium Id',
        placeholder: 'Ingresa stadium id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Stadium Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 5,
      },
      {
        icon: 'pi pi-database',
        key: 'start_time',
        type: TypeFields.DATE,
        label: 'Start Time',
        placeholder: 'Ingresa start time',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Start Time',
        value: '',
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.DATE,
        order: 6,
      },
    ],
  },
  matchPeriodForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'catalog_id',
        type: TypeFields.NUMBER,
        label: 'Catalog Id',
        placeholder: 'Ingresa catalog id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Catalog Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'first_team_score',
        type: TypeFields.NUMBER,
        label: 'First Team Score',
        placeholder: 'Ingresa first team score',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'First Team Score',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'match_id',
        type: TypeFields.NUMBER,
        label: 'Match Id',
        placeholder: 'Ingresa match id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Match Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'second_team_score',
        type: TypeFields.NUMBER,
        label: 'Second Team Score',
        placeholder: 'Ingresa second team score',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Second Team Score',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 4,
      },
    ],
  },
  permissionForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'description',
        type: TypeFields.TEXT,
        label: 'Description',
        placeholder: 'Ingresa description',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Description',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Name',
        placeholder: 'Ingresa name',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Name',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'permission_id',
        type: TypeFields.NUMBER,
        label: 'Permission Id',
        placeholder: 'Ingresa permission id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Permission Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
    ],
  },
  predictionForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'first_team_score',
        type: TypeFields.NUMBER,
        label: 'First Team Score',
        placeholder: 'Ingresa first team score',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'First Team Score',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'match_id',
        type: TypeFields.NUMBER,
        label: 'Match Id',
        placeholder: 'Ingresa match id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Match Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'second_team_score',
        type: TypeFields.NUMBER,
        label: 'Second Team Score',
        placeholder: 'Ingresa second team score',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Second Team Score',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'turn',
        type: TypeFields.NUMBER,
        label: 'Turn',
        placeholder: 'Ingresa turn',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Turn',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 4,
      },
      {
        icon: 'pi pi-database',
        key: 'user_league_id',
        type: TypeFields.NUMBER,
        label: 'User League Id',
        placeholder: 'Ingresa user league id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User League Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 5,
      },
    ],
  },
  roleForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'description',
        type: TypeFields.TEXT,
        label: 'Description',
        placeholder: 'Ingresa description',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Description',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Name',
        placeholder: 'Ingresa name',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Name',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'role_id',
        type: TypeFields.NUMBER,
        label: 'Role Id',
        placeholder: 'Ingresa role id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Role Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
    ],
  },
  rolePermissionForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'permission_id',
        type: TypeFields.NUMBER,
        label: 'Permission Id',
        placeholder: 'Ingresa permission id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Permission Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'role_id',
        type: TypeFields.NUMBER,
        label: 'Role Id',
        placeholder: 'Ingresa role id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Role Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
    ],
  },
  rulesLeagueForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'description',
        type: TypeFields.TEXT,
        label: 'Description',
        placeholder: 'Ingresa description',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Description',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'dimension',
        type: TypeFields.TEXT,
        label: 'Dimension',
        placeholder: 'Ingresa dimension',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Dimension',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'league_id',
        type: TypeFields.NUMBER,
        label: 'League Id',
        placeholder: 'Ingresa league id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'League Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'value',
        type: TypeFields.TEXT,
        label: 'Value',
        placeholder: 'Ingresa value',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Value',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 4,
      },
    ],
  },
  transactionForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'amount',
        type: TypeFields.NUMBER,
        label: 'Amount',
        placeholder: 'Ingresa amount',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Amount',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'catalog_id',
        type: TypeFields.NUMBER,
        label: 'Catalog Id',
        placeholder: 'Ingresa catalog id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Catalog Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'description',
        type: TypeFields.TEXT,
        label: 'Description',
        placeholder: 'Ingresa description',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Description',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'transaction_date',
        type: TypeFields.DATE,
        label: 'Transaction Date',
        placeholder: 'Ingresa transaction date',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Transaction Date',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.DATE,
        order: 4,
      },
      {
        icon: 'pi pi-database',
        key: 'wallet_id',
        type: TypeFields.NUMBER,
        label: 'Wallet Id',
        placeholder: 'Ingresa wallet id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Wallet Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 5,
      },
    ],
  },
  userForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'email',
        type: TypeFields.EMAIL,
        label: 'Email',
        placeholder: 'Ingresa email',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Email',
        value: '',
        rules: [Validators.required, Validators.email],
        options: [],
        controlType: TypeFields.EMAIL,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'login',
        type: TypeFields.TEXT,
        label: 'Login',
        placeholder: 'Ingresa login',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Login',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Name',
        placeholder: 'Ingresa name',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Name',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'password_hash',
        type: TypeFields.PASSWORD,
        label: 'Password Hash',
        placeholder: 'Ingresa password hash',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Password Hash',
        value: '',
        rules: [Validators.required, Validators.minLength(6)],
        options: [],
        controlType: TypeFields.PASSWORD,
        order: 4,
      },
      {
        icon: 'pi pi-database',
        key: 'registration_date',
        type: TypeFields.DATE,
        label: 'Registration Date',
        placeholder: 'Ingresa registration date',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Registration Date',
        value: '',
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.DATE,
        order: 5,
      },
      {
        icon: 'pi pi-database',
        key: 'status',
        type: TypeFields.TEXT,
        label: 'Status',
        placeholder: 'Ingresa status',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Status',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 6,
      },
      {
        icon: 'pi pi-database',
        key: 'user_id',
        type: TypeFields.NUMBER,
        label: 'User Id',
        placeholder: 'Ingresa user id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 7,
      },
    ],
  },
  userLeagueForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'accumulated_points',
        type: TypeFields.NUMBER,
        label: 'Accumulated Points',
        placeholder: 'Ingresa accumulated points',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Accumulated Points',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'league_id',
        type: TypeFields.NUMBER,
        label: 'League Id',
        placeholder: 'Ingresa league id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'League Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'user_id',
        type: TypeFields.NUMBER,
        label: 'User Id',
        placeholder: 'Ingresa user id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'user_league_id',
        type: TypeFields.NUMBER,
        label: 'User League Id',
        placeholder: 'Ingresa user league id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User League Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 4,
      },
    ],
  },
  userLeagueRewardForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'amount',
        type: TypeFields.NUMBER,
        label: 'Amount',
        placeholder: 'Ingresa amount',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Amount',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'payment_date',
        type: TypeFields.DATE,
        label: 'Payment Date',
        placeholder: 'Ingresa payment date',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Payment Date',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.DATE,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'status',
        type: TypeFields.TEXT,
        label: 'Status',
        placeholder: 'Ingresa status',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Status',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'user_league_id',
        type: TypeFields.NUMBER,
        label: 'User League Id',
        placeholder: 'Ingresa user league id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User League Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 4,
      },
    ],
  },
  userRoleForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'role_id',
        type: TypeFields.NUMBER,
        label: 'Role Id',
        placeholder: 'Ingresa role id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Role Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'user_id',
        type: TypeFields.NUMBER,
        label: 'User Id',
        placeholder: 'Ingresa user id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
    ],
  },
  userSessionForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'ip_address',
        type: TypeFields.TEXT,
        label: 'Ip Address',
        placeholder: 'Ingresa ip address',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Ip Address',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'login',
        type: TypeFields.TEXT,
        label: 'Login',
        placeholder: 'Ingresa login',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Login',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'sign_in',
        type: TypeFields.TEXT,
        label: 'Sign In',
        placeholder: 'Ingresa sign in',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Sign In',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'sign_out',
        type: TypeFields.TEXT,
        label: 'Sign Out',
        placeholder: 'Ingresa sign out',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Sign Out',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 4,
      },
      {
        icon: 'pi pi-database',
        key: 'user_agent',
        type: TypeFields.TEXT,
        label: 'User Agent',
        placeholder: 'Ingresa user agent',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User Agent',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 5,
      },
      {
        icon: 'pi pi-database',
        key: 'user_id',
        type: TypeFields.NUMBER,
        label: 'User Id',
        placeholder: 'Ingresa user id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 6,
      },
    ],
  },
  walletForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'balance',
        type: TypeFields.NUMBER,
        label: 'Balance',
        placeholder: 'Ingresa balance',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Balance',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'status',
        type: TypeFields.TEXT,
        label: 'Status',
        placeholder: 'Ingresa status',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Status',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'user_id',
        type: TypeFields.NUMBER,
        label: 'User Id',
        placeholder: 'Ingresa user id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'wallet_id',
        type: TypeFields.NUMBER,
        label: 'Wallet Id',
        placeholder: 'Ingresa wallet id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Wallet Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 4,
      },
    ],
  },
  worldLeagueForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Name',
        placeholder: 'Ingresa name',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Name',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'world_league_id',
        type: TypeFields.NUMBER,
        label: 'World League Id',
        placeholder: 'Ingresa world league id',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'World League Id',
        value: 0,
        rules: [],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 2,
      },
    ],
  },
  loginForm: {
    fields: [
      {
        icon: 'pi pi-user',
        key: 'email',
        type: TypeFields.EMAIL,
        label: 'Correo Electrónico',
        placeholder: 'Ingresa tu correo electrónico',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Correo electrónico para iniciar sesión',
        value: '',
        rules: [Validators.required, Validators.email],
        options: [],
        controlType: TypeFields.EMAIL,
        order: 1,
      },
      {
        icon: 'pi pi-lock',
        key: 'password',
        type: TypeFields.PASSWORD,
        label: 'Contraseña',
        placeholder: 'Ingresa tu contraseña',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Contraseña para iniciar sesión',
        value: '',
        rules: [Validators.required, Validators.minLength(6)],
        options: [],
        controlType: TypeFields.PASSWORD,
        order: 2,
      },
    ],
  },
  registerForm: {
    fields: [
      {
        icon: 'pi pi-envelope',
        key: 'email',
        type: TypeFields.EMAIL,
        label: 'Correo Electrónico',
        placeholder: 'Ingresa tu correo electrónico',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Se usará para validar tu cuenta',
        value: '',
        rules: [Validators.required, Validators.email],
        options: [],
        controlType: TypeFields.EMAIL,
        order: 1,
      },
      {
        icon: 'pi pi-lock',
        key: 'password',
        type: TypeFields.PASSWORD,
        label: 'Contraseña',
        placeholder: 'Crea tu contraseña',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Mínimo 6 caracteres',
        value: '',
        rules: [Validators.required, Validators.minLength(6)],
        options: [],
        controlType: TypeFields.PASSWORD,
        order: 2,
      },
    ],
  },
  changePasswordForm: {
    fields: [
      {
        icon: 'pi pi-envelope',
        key: 'email',
        type: TypeFields.EMAIL,
        label: 'Correo Electrónico',
        placeholder: 'Ingresa tu correo electrónico',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Te enviaremos un enlace para restablecer tu contraseña',
        value: '',
        rules: [Validators.required, Validators.email],
        options: [],
        controlType: TypeFields.EMAIL,
        order: 1,
      },
    ],
  },
  updatePasswordForm: {
    fields: [
      {
        icon: 'pi pi-lock',
        key: 'newPassword',
        type: TypeFields.PASSWORD,
        label: 'Nueva Contraseña',
        placeholder: 'Ingresa tu nueva contraseña',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Debe tener al menos 6 caracteres',
        value: '',
        rules: [Validators.required, Validators.minLength(6)],
        options: [],
        controlType: TypeFields.PASSWORD,
        order: 1,
      },
    ],
  },
};
