import { Validators } from '@angular/forms';
import { TypeFields } from '../../../shared/features/dynamic-form/enums/type-fields';
import { FormFields } from '../../../shared/features/dynamic-form/interfaces/field-props';

export const formFields: FormFields = {
  leagueForm: {
    fields: [
      {
        icon: 'pi pi-database',
        key: 'catalog_id',
        type: TypeFields.SELECT,
        label: 'Tipo de liga',
        placeholder: 'Selecciona tipo de liga',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Tipo de liga',
        value: 0,
        rules: [Validators.required],
        options: [],
        optionsSource: {
          table: 'CATALOG',
          valueField: 'catalog_id',
          labelField: 'description',
          orderBy: 'description',
          order: 'asc',
          includeDeleted: false,
        },
        controlType: TypeFields.SELECT,
        order: 1,
      },
      {
        icon: 'pi pi-database',
        key: 'invitation_code',
        type: TypeFields.TEXT,
        label: 'Invitation Code',
        placeholder: 'Ingresa invitation code',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Invitation Code',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 2,
      },
      {
        icon: 'pi pi-database',
        key: 'name',
        type: TypeFields.TEXT,
        label: 'Name',
        placeholder: 'Ingresa name',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Name',
        value: '',
        rules: [Validators.required, Validators.minLength(2)],
        options: [],
        controlType: TypeFields.TEXT,
        order: 3,
      },
      {
        icon: 'pi pi-database',
        key: 'status',
        type: TypeFields.TEXT,
        label: 'Status',
        placeholder: 'Ingresa status',
        state: {
          required: false,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'Status',
        value: '',
        rules: [],
        options: [],
        controlType: TypeFields.TEXT,
        order: 5,
      },
      {
        icon: 'pi pi-database',
        key: 'user_id',
        type: TypeFields.NUMBER,
        label: 'User Id',
        placeholder: 'Ingresa user id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'User Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 6,
      },
      {
        icon: 'pi pi-database',
        key: 'world_league_id',
        type: TypeFields.NUMBER,
        label: 'World League Id',
        placeholder: 'Ingresa world league id',
        state: {
          required: true,
          disabled: false,
          hidden: false,
          readonly: false,
          repeatible: { repeat: false, minItems: 1, maxItems: 1 },
        },
        hint: 'World League Id',
        value: 0,
        rules: [Validators.required],
        options: [],
        controlType: TypeFields.NUMBER,
        order: 7,
      },
    ],
  },
};
