-- ===================================================================
-- Migration: Magic Links + Push Notifications (In-App Inbox) + Prediction Lock
-- Date: 2026-05-11 (Updated: App-based inbox, Browser Notifications API)
-- Description: Add tables for anonymous user invitations and in-app notifications
-- ===================================================================

-- 1. MAGIC_LINK Table: For anonymous user invitations
CREATE TABLE "MAGIC_LINK" (
  "magic_link_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "token" varchar UNIQUE NOT NULL,
  "email" varchar NOT NULL,
  "league_id" int NOT NULL,
  "created_by" int,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expires_at" timestamp NOT NULL,
  "used_at" timestamp,
  "used_by" int,
  "status" varchar NOT NULL DEFAULT 'pending', -- pending, used, expired
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp,
  "deleted_by" int,
  "updated_at" timestamp,
  "updated_by" int,
  CONSTRAINT fk_magic_link_league FOREIGN KEY ("league_id")
    REFERENCES "LEAGUE"("league_id") ON DELETE RESTRICT,
  CONSTRAINT fk_magic_link_created_by FOREIGN KEY ("created_by")
    REFERENCES "USER"("user_id") ON DELETE SET NULL,
  CONSTRAINT fk_magic_link_used_by FOREIGN KEY ("used_by")
    REFERENCES "USER"("user_id") ON DELETE SET NULL
);

CREATE INDEX idx_magic_link_token ON "MAGIC_LINK"("token");
CREATE INDEX idx_magic_link_email ON "MAGIC_LINK"("email");
CREATE INDEX idx_magic_link_league_id ON "MAGIC_LINK"("league_id");
CREATE INDEX idx_magic_link_status ON "MAGIC_LINK"("status");

-- 2. NOTIFICATION_INBOX Table: In-app notification bandeja for users
CREATE TABLE "NOTIFICATION_INBOX" (
  "notification_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "league_id" int,
  "match_id" int,
  "notification_type" varchar NOT NULL,
    -- match_reminder: 15 min antes del partido
    -- prediction_locked: Predicciones bloqueadas
    -- result_posted: Resultado publicado
    -- league_update: Actualización de la liga
    -- invitation_received: Invitación a liga
    -- league_created: Nueva liga creada
  "title" varchar NOT NULL,
  "body" text NOT NULL,
  "icon" varchar, -- URL to notification icon
  "action_url" varchar, -- Internal app route to navigate
  "payload" jsonb, -- Additional data as JSON
  "priority" varchar NOT NULL DEFAULT 'normal', -- low, normal, high, urgent
  "is_read" boolean NOT NULL DEFAULT false,
  "read_at" timestamp,
  "read_by" int,
  "browser_notification_sent" boolean NOT NULL DEFAULT false,
  "browser_notification_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_by" int NOT NULL,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp,
  "deleted_by" int,
  "updated_at" timestamp,
  "updated_by" int,
  CONSTRAINT fk_notif_user FOREIGN KEY ("user_id")
    REFERENCES "USER"("user_id") ON DELETE CASCADE,
  CONSTRAINT fk_notif_league FOREIGN KEY ("league_id")
    REFERENCES "LEAGUE"("league_id") ON DELETE SET NULL,
  CONSTRAINT fk_notif_match FOREIGN KEY ("match_id")
    REFERENCES "MATCH"("match_id") ON DELETE SET NULL,
  CONSTRAINT fk_notif_created_by FOREIGN KEY ("created_by")
    REFERENCES "USER"("user_id") ON DELETE RESTRICT
);

CREATE INDEX idx_notif_user_id ON "NOTIFICATION_INBOX"("user_id");
CREATE INDEX idx_notif_user_read ON "NOTIFICATION_INBOX"("user_id", "is_read");
CREATE INDEX idx_notif_created_at ON "NOTIFICATION_INBOX"("created_at");
CREATE INDEX idx_notif_type ON "NOTIFICATION_INBOX"("notification_type");
CREATE INDEX idx_notif_priority ON "NOTIFICATION_INBOX"("priority");
CREATE INDEX idx_notif_deleted ON "NOTIFICATION_INBOX"("is_deleted");

-- 3. BROWSER_NOTIFICATION_LOG Table: Audit log for browser notifications sent
CREATE TABLE "BROWSER_NOTIFICATION_LOG" (
  "browser_notif_log_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notification_id" int NOT NULL,
  "user_id" int NOT NULL,
  "browser_title" varchar NOT NULL,
  "browser_body" varchar NOT NULL,
  "browser_icon" varchar,
  "browser_badge" varchar,
  "browser_tag" varchar, -- For grouping notifications
  "sent_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "success" boolean NOT NULL DEFAULT false,
  "error_message" varchar,
  "created_by" int NOT NULL,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp,
  "deleted_by" int,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "updated_by" int,
  CONSTRAINT fk_browser_log_notif FOREIGN KEY ("notification_id")
    REFERENCES "NOTIFICATION_INBOX"("notification_id") ON DELETE CASCADE,
  CONSTRAINT fk_browser_log_user FOREIGN KEY ("user_id")
    REFERENCES "USER"("user_id") ON DELETE CASCADE,
  CONSTRAINT fk_browser_log_created_by FOREIGN KEY ("created_by")
    REFERENCES "USER"("user_id") ON DELETE RESTRICT
);

CREATE INDEX idx_browser_log_notif_id ON "BROWSER_NOTIFICATION_LOG"("notification_id");
CREATE INDEX idx_browser_log_user_id ON "BROWSER_NOTIFICATION_LOG"("user_id");
CREATE INDEX idx_browser_log_sent_at ON "BROWSER_NOTIFICATION_LOG"("sent_at");

-- 4. ERROR_CATALOG Table: Registry of error numbers and descriptions
CREATE TABLE "ERROR_CATALOG" (
  "error_number" int PRIMARY KEY,
  "integration" varchar NOT NULL,
  "description" text NOT NULL,
  "severity" varchar NOT NULL DEFAULT 'medium', -- low, medium, high, critical
  "resolution" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_by" int,
  "updated_at" timestamp,
  "updated_by" int,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp,
  "deleted_by" int,
  CONSTRAINT fk_error_catalog_created_by FOREIGN KEY ("created_by")
    REFERENCES "USER"("user_id") ON DELETE SET NULL,
  CONSTRAINT fk_error_catalog_updated_by FOREIGN KEY ("updated_by")
    REFERENCES "USER"("user_id") ON DELETE SET NULL,
  CONSTRAINT fk_error_catalog_deleted_by FOREIGN KEY ("deleted_by")
    REFERENCES "USER"("user_id") ON DELETE SET NULL
);

CREATE INDEX idx_error_catalog_integration ON "ERROR_CATALOG"("integration");
CREATE INDEX idx_error_catalog_severity ON "ERROR_CATALOG"("severity");
CREATE INDEX idx_error_catalog_active ON "ERROR_CATALOG"("is_active");

-- 5. ERROR_LOG Table: Runtime and application error registry
CREATE TABLE "ERROR_LOG" (
  "error_log_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "error_number" int NOT NULL,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "stack_trace" text,
  "source_file" varchar,
  "source_line" int,
  "route" varchar,
  "user_id" int,
  "browser_user_agent" text,
  "context" jsonb,
  "severity" varchar NOT NULL DEFAULT 'medium',
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_by" int,
  "updated_at" timestamp,
  "updated_by" int,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp,
  "deleted_by" int,
  CONSTRAINT fk_error_log_catalog FOREIGN KEY ("error_number")
    REFERENCES "ERROR_CATALOG"("error_number") ON DELETE RESTRICT,
  CONSTRAINT fk_error_log_user FOREIGN KEY ("user_id")
    REFERENCES "USER"("user_id") ON DELETE SET NULL,
  CONSTRAINT fk_error_log_created_by FOREIGN KEY ("created_by")
    REFERENCES "USER"("user_id") ON DELETE SET NULL,
  CONSTRAINT fk_error_log_updated_by FOREIGN KEY ("updated_by")
    REFERENCES "USER"("user_id") ON DELETE SET NULL,
  CONSTRAINT fk_error_log_deleted_by FOREIGN KEY ("deleted_by")
    REFERENCES "USER"("user_id") ON DELETE SET NULL
);

CREATE INDEX idx_error_log_error_number ON "ERROR_LOG"("error_number");
CREATE INDEX idx_error_log_created_at ON "ERROR_LOG"("created_at");
CREATE INDEX idx_error_log_severity ON "ERROR_LOG"("severity");
CREATE INDEX idx_error_log_user_id ON "ERROR_LOG"("user_id");
CREATE INDEX idx_error_log_deleted ON "ERROR_LOG"("is_deleted");

ALTER TABLE "ERROR_CATALOG" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ERROR_LOG" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "error_catalog_read" ON "ERROR_CATALOG"
  FOR SELECT USING (has_permission('audit_log:read'));

CREATE POLICY "error_catalog_write" ON "ERROR_CATALOG"
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "error_catalog_update" ON "ERROR_CATALOG"
  FOR UPDATE USING (has_permission('audit_log:update'))
  WITH CHECK (has_permission('audit_log:update'));

CREATE POLICY "error_log_read" ON "ERROR_LOG"
  FOR SELECT USING (has_permission('audit_log:read'));

CREATE POLICY "error_log_insert" ON "ERROR_LOG"
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "error_log_update" ON "ERROR_LOG"
  FOR UPDATE USING (has_permission('audit_log:update'))
  WITH CHECK (has_permission('audit_log:update'));

CREATE POLICY "error_log_delete" ON "ERROR_LOG"
  FOR DELETE USING (has_permission('audit_log:delete'));

-- 4. PREDICTION_LOCK Table: Track locked predictions before match start
CREATE TABLE "PREDICTION_LOCK" (
  "prediction_lock_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "match_id" int NOT NULL,
  "locked_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "lock_reason" varchar NOT NULL DEFAULT 'auto_15min', -- auto_15min, manual_admin
  "locked_by" int,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp,
  "deleted_by" int,
  "created_by" int,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "updated_by" int,
  CONSTRAINT fk_pred_lock_match FOREIGN KEY ("match_id")
    REFERENCES "MATCH"("match_id") ON DELETE RESTRICT
);

CREATE INDEX idx_pred_lock_match_id ON "PREDICTION_LOCK"("match_id");
CREATE INDEX idx_pred_lock_locked_at ON "PREDICTION_LOCK"("locked_at");

-- ===================================================================
-- AUDIT LOG TRIGGERS for new tables
-- ===================================================================

-- Trigger para MAGIC_LINK
CREATE OR REPLACE FUNCTION audit_magic_link()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO "AUDIT_LOG" (
    "table_name", "operation_type", "old_values", "new_values",
    "created_by", "created_at", "user_session_id"
  ) VALUES (
    'MAGIC_LINK',
    CASE
      WHEN TG_OP = 'INSERT' THEN 'I'
      WHEN TG_OP = 'UPDATE' THEN 'U'
      WHEN TG_OP = 'DELETE' THEN 'D'
    END,
    CASE WHEN TG_OP = 'DELETE' THEN row_to_json(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN row_to_json(NEW) ELSE NULL END,
    COALESCE(NEW.created_by, OLD.created_by),
    CURRENT_TIMESTAMP,
    NULL
  );
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_audit_magic_link
  AFTER INSERT OR UPDATE OR DELETE ON "MAGIC_LINK"
  FOR EACH ROW EXECUTE FUNCTION audit_magic_link();

-- Trigger para NOTIFICATION_INBOX
CREATE OR REPLACE FUNCTION audit_notification_inbox()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO "AUDIT_LOG" (
    "table_name", "operation_type", "old_values", "new_values",
    "created_by", "created_at", "user_session_id"
  ) VALUES (
    'NOTIFICATION_INBOX',
    CASE
      WHEN TG_OP = 'INSERT' THEN 'I'
      WHEN TG_OP = 'UPDATE' THEN 'U'
      WHEN TG_OP = 'DELETE' THEN 'D'
    END,
    CASE WHEN TG_OP = 'DELETE' THEN row_to_json(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN row_to_json(NEW) ELSE NULL END,
    COALESCE(NEW.created_by, OLD.created_by),
    CURRENT_TIMESTAMP,
    NULL
  );
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_audit_notification_inbox
  AFTER INSERT OR UPDATE OR DELETE ON "NOTIFICATION_INBOX"
  FOR EACH ROW EXECUTE FUNCTION audit_notification_inbox();

-- Trigger para BROWSER_NOTIFICATION_LOG
CREATE OR REPLACE FUNCTION audit_browser_notification_log()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO "AUDIT_LOG" (
    "table_name", "operation_type", "old_values", "new_values",
    "created_by", "created_at", "user_session_id"
  ) VALUES (
    'BROWSER_NOTIFICATION_LOG',
    CASE
      WHEN TG_OP = 'INSERT' THEN 'I'
      WHEN TG_OP = 'UPDATE' THEN 'U'
      WHEN TG_OP = 'DELETE' THEN 'D'
    END,
    CASE WHEN TG_OP = 'DELETE' THEN row_to_json(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN row_to_json(NEW) ELSE NULL END,
    COALESCE(NEW.created_by, OLD.created_by),
    CURRENT_TIMESTAMP,
    NULL
  );
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_audit_browser_notification_log
  AFTER INSERT OR UPDATE OR DELETE ON "BROWSER_NOTIFICATION_LOG"
  FOR EACH ROW EXECUTE FUNCTION audit_browser_notification_log();

-- Trigger para ERROR_CATALOG
CREATE OR REPLACE FUNCTION audit_error_catalog()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO "AUDIT_LOG" (
    "table_name", "operation_type", "old_values", "new_values",
    "created_by", "created_at", "user_session_id"
  ) VALUES (
    'ERROR_CATALOG',
    CASE
      WHEN TG_OP = 'INSERT' THEN 'I'
      WHEN TG_OP = 'UPDATE' THEN 'U'
      WHEN TG_OP = 'DELETE' THEN 'D'
    END,
    CASE WHEN TG_OP = 'DELETE' THEN row_to_json(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN row_to_json(NEW) ELSE NULL END,
    COALESCE(NEW.created_by, OLD.created_by),
    CURRENT_TIMESTAMP,
    NULL
  );
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_audit_error_catalog
  AFTER INSERT OR UPDATE OR DELETE ON "ERROR_CATALOG"
  FOR EACH ROW EXECUTE FUNCTION audit_error_catalog();

-- Trigger para ERROR_LOG
CREATE OR REPLACE FUNCTION audit_error_log()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO "AUDIT_LOG" (
    "table_name", "operation_type", "old_values", "new_values",
    "created_by", "created_at", "user_session_id"
  ) VALUES (
    'ERROR_LOG',
    CASE
      WHEN TG_OP = 'INSERT' THEN 'I'
      WHEN TG_OP = 'UPDATE' THEN 'U'
      WHEN TG_OP = 'DELETE' THEN 'D'
    END,
    CASE WHEN TG_OP = 'DELETE' THEN row_to_json(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN row_to_json(NEW) ELSE NULL END,
    COALESCE(NEW.created_by, OLD.created_by),
    CURRENT_TIMESTAMP,
    NULL
  );
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_audit_error_log
  AFTER INSERT OR UPDATE OR DELETE ON "ERROR_LOG"
  FOR EACH ROW EXECUTE FUNCTION audit_error_log();

-- Trigger para PREDICTION_LOCK
CREATE OR REPLACE FUNCTION audit_prediction_lock()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO "AUDIT_LOG" (
    "table_name", "operation_type", "old_values", "new_values",
    "created_by", "created_at", "user_session_id"
  ) VALUES (
    'PREDICTION_LOCK',
    CASE
      WHEN TG_OP = 'INSERT' THEN 'I'
      WHEN TG_OP = 'UPDATE' THEN 'U'
      WHEN TG_OP = 'DELETE' THEN 'D'
    END,
    CASE WHEN TG_OP = 'DELETE' THEN row_to_json(OLD) ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN row_to_json(NEW) ELSE NULL END,
    COALESCE(NEW.created_by, OLD.created_by),
    CURRENT_TIMESTAMP,
    NULL
  );
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_audit_prediction_lock
  AFTER INSERT OR UPDATE OR DELETE ON "PREDICTION_LOCK"
  FOR EACH ROW EXECUTE FUNCTION audit_prediction_lock();

