CREATE TABLE "USER" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login" varchar UNIQUE,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "registration_date" timestamp NOT NULL,
  "status" varchar NOT NULL,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ROLE" (
  "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" varchar,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "PERMISSION" (
  "permission_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" varchar,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "ROLE_PERMISSION" (
  "role_permission_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" int NOT NULL,
  "permission_id" int NOT NULL,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "USER_ROLE" (
  "user_role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "role_id" int NOT NULL,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "LEAGUE" (
  "league_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "world_league_id" int NOT NULL,
  "user_id" int NOT NULL,
  "name" varchar UNIQUE NOT NULL,
  "catalog_id" int NOT NULL,
  "invitation_code" varchar UNIQUE,
  "status" varchar,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "WORLD_LEAGUE" (
  "world_league_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "LEAGUE_REWARD" (
  "league_reward_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "league_id" int NOT NULL,
  "mundial_id" int NOT NULL,
  "total_collected_amount" decimal,
  "platform_fee_5pct" decimal,
  "global_prize_1pct" decimal,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "RULES_LEAGUE" (
  "rules_league_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "league_id" int NOT NULL,
  "description" varchar UNIQUE NOT NULL,
  "value" varchar NOT NULL,
  "dimension" varchar NOT NULL,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "USER_LEAGUE" (
  "user_league_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "league_id" int NOT NULL,
  "user_id" int NOT NULL,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp,
  "accumulated_points" int NOT NULL
);

CREATE TABLE "INVITATION" (
  "invitation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_league_id" int NOT NULL,
  "token" varchar UNIQUE,
  "status" varchar,
  "send_date" timestamp,
  "expiration_date" timestamp,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "TEAM" (
  "team_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "catalog_id" int NOT NULL,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "CATALOG" (
  "catalog_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "table_id" int NOT NULL,
  "table_name" varchar NOT NULL,
  "neumonic" varchar UNIQUE NOT NULL,
  "description" varchar NOT NULL,
  "value" varchar NOT NULL,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "MATCH" (
  "match_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "start_time" timestamp NOT NULL,
  "stadium_id" int NOT NULL,
  "league_id" int NOT NULL,
  "first_team_id" int NOT NULL,
  "second_team_id" int NOT NULL,
  "first_team_total" int NOT NULL,
  "second_team_total" int NOT NULL,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "MATCH_PERIOD" (
  "period_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "match_id" int NOT NULL,
  "catalog_id" int NOT NULL,
  "first_team_score" int DEFAULT 0,
  "second_team_score" int DEFAULT 0,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "PREDICTION" (
  "prediction_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_league_id" int NOT NULL,
  "match_id" int NOT NULL,
  "turn" int NOT NULL DEFAULT 0,
  "first_team_score" int NOT NULL DEFAULT 0,
  "second_team_score" int NOT NULL DEFAULT 0,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "STADIUM" (
  "stadium_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "catalog_id" int NOT NULL,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "USER_LEAGUE_REWARD" (
  "league_user_reward_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_league_id" int UNIQUE,
  "amount" decimal,
  "payment_date" timestamp,
  "status" varchar,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "WALLET" (
  "wallet_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "balance" decimal NOT NULL,
  "status" varchar,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "TRANSACTION" (
  "transaction_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "wallet_id" int NOT NULL,
  "amount" decimal NOT NULL,
  "transaction_date" timestamp,
  "catalog_id" int NOT NULL,
  "description" varchar,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "AUDIT_LOG" (
  "audit_log_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "table_name" varchar NOT NULL,
  "operation_type" char NOT NULL,
  "old_values" text,
  "new_values" text,
  "user_session_id" int NOT NULL,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp
);

CREATE TABLE "USER_SESSION" (
  "user_session_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" varchar NOT NULL,
  "user_id" int NOT NULL,
  "login" varchar NOT NULL,
  "ip_address" varchar NOT NULL,
  "user_agent" varchar,
  "created_by" int,
  "created_at" timestamp NOT NULL,
  "updated_by" int,
  "updated_at" timestamp,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "deleted_at" timestamp,
  "sign_in" timestamp,
  "sign_out" timestamp
);

CREATE INDEX "idx_user_email" ON "USER" ("email");

CREATE INDEX "idx_user_login" ON "USER" ("login");

CREATE INDEX "idx_league_admin" ON "LEAGUE" ("user_id");

CREATE UNIQUE INDEX "uq_user_league" ON "USER_LEAGUE" ("league_id", "user_id");

CREATE INDEX "idx_user_league_league" ON "USER_LEAGUE" ("league_id");

CREATE INDEX "idx_user_league_user" ON "USER_LEAGUE" ("user_id");

CREATE INDEX "idx_match_league" ON "MATCH" ("league_id");

CREATE UNIQUE INDEX "uq_prediction" ON "PREDICTION" ("user_league_id", "match_id");

CREATE INDEX "idx_prediction_match" ON "PREDICTION" ("match_id");

CREATE INDEX "idx_audit_session" ON "AUDIT_LOG" ("user_session_id");

CREATE INDEX "idx_audit_table" ON "AUDIT_LOG" ("table_name");

CREATE INDEX "idx_audit_date" ON "AUDIT_LOG" ("created_at");

CREATE INDEX "idx_session_user" ON "USER_SESSION" ("user_id");

ALTER TABLE "AUDIT_LOG" ADD FOREIGN KEY ("user_session_id") REFERENCES "USER_SESSION" ("user_session_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ROLE_PERMISSION" ADD FOREIGN KEY ("role_id") REFERENCES "ROLE" ("role_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ROLE_PERMISSION" ADD FOREIGN KEY ("permission_id") REFERENCES "PERMISSION" ("permission_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "USER_ROLE" ADD FOREIGN KEY ("user_id") REFERENCES "USER" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "USER_ROLE" ADD FOREIGN KEY ("role_id") REFERENCES "ROLE" ("role_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "LEAGUE" ADD FOREIGN KEY ("user_id") REFERENCES "USER" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "LEAGUE_REWARD" ADD FOREIGN KEY ("league_id") REFERENCES "LEAGUE" ("league_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "LEAGUE" ADD FOREIGN KEY ("catalog_id") REFERENCES "CATALOG" ("catalog_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TEAM" ADD FOREIGN KEY ("catalog_id") REFERENCES "CATALOG" ("catalog_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "STADIUM" ADD FOREIGN KEY ("catalog_id") REFERENCES "CATALOG" ("catalog_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MATCH_PERIOD" ADD FOREIGN KEY ("catalog_id") REFERENCES "CATALOG" ("catalog_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TRANSACTION" ADD FOREIGN KEY ("catalog_id") REFERENCES "CATALOG" ("catalog_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RULES_LEAGUE" ADD FOREIGN KEY ("league_id") REFERENCES "LEAGUE" ("league_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "USER_LEAGUE" ADD FOREIGN KEY ("league_id") REFERENCES "LEAGUE" ("league_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "USER_LEAGUE" ADD FOREIGN KEY ("user_id") REFERENCES "USER" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "INVITATION" ADD FOREIGN KEY ("user_league_id") REFERENCES "USER_LEAGUE" ("user_league_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MATCH" ADD FOREIGN KEY ("stadium_id") REFERENCES "STADIUM" ("stadium_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MATCH" ADD FOREIGN KEY ("league_id") REFERENCES "LEAGUE" ("league_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MATCH_PERIOD" ADD FOREIGN KEY ("match_id") REFERENCES "MATCH" ("match_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MATCH" ADD FOREIGN KEY ("first_team_id") REFERENCES "TEAM" ("team_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "MATCH" ADD FOREIGN KEY ("second_team_id") REFERENCES "TEAM" ("team_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PREDICTION" ADD FOREIGN KEY ("user_league_id") REFERENCES "USER_LEAGUE" ("user_league_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PREDICTION" ADD FOREIGN KEY ("match_id") REFERENCES "MATCH" ("match_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "LEAGUE" ADD FOREIGN KEY ("world_league_id") REFERENCES "WORLD_LEAGUE" ("world_league_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "USER_LEAGUE_REWARD" ADD FOREIGN KEY ("user_league_id") REFERENCES "USER_LEAGUE" ("user_league_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "USER_SESSION" ADD FOREIGN KEY ("user_id") REFERENCES "USER" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "USER" ADD FOREIGN KEY ("user_id") REFERENCES "WALLET" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TRANSACTION" ADD FOREIGN KEY ("wallet_id") REFERENCES "WALLET" ("wallet_id") DEFERRABLE INITIALLY IMMEDIATE;


