-- v3.21 · Stadium images — logo_url for WC2026 venues (Wikimedia Commons)
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Vista_a%C3%A9rea_del_Estadio_Azteca_-_2026_-_02.jpg/330px-Vista_a%C3%A9rea_del_Estadio_Azteca_-_2026_-_02.jpg'                               WHERE stadium_id = 42;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Mexico_Guadalupe_Monterrey_Estadio_BBVA_Bancomer_fifa_world_cup_2026_6.JPG/330px-Mexico_Guadalupe_Monterrey_Estadio_BBVA_Bancomer_fifa_world_cup_2026_6.JPG' WHERE stadium_id = 43;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Estadio_Akron_02-07-2022_cabecera_sur_lado_derecho_%283%29.jpg/330px-Estadio_Akron_02-07-2022_cabecera_sur_lado_derecho_%283%29.jpg'                 WHERE stadium_id = 44;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Arlington_June_2020_4_%28AT%26T_Stadium%29.jpg/330px-Arlington_June_2020_4_%28AT%26T_Stadium%29.jpg'                                                   WHERE stadium_id = 45;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Metlife_stadium_%28Aerial_view%29.jpg/330px-Metlife_stadium_%28Aerial_view%29.jpg'                                                                     WHERE stadium_id = 46;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Mercedes_Benz_Stadium_time_lapse_capture_2017-08-13.jpg/330px-Mercedes_Benz_Stadium_time_lapse_capture_2017-08-13.jpg'                                 WHERE stadium_id = 47;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Aerial_view_of_Arrowhead_Stadium_08-31-2013.jpg/330px-Aerial_view_of_Arrowhead_Stadium_08-31-2013.jpg'                                                 WHERE stadium_id = 48;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Nrg_stadium.jpg/330px-Nrg_stadium.jpg'                                                                                                                 WHERE stadium_id = 49;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Levi%27s_Stadium_in_February_2016_prior_to_Super_Bowl_50_%2824398261729%29.jpg/330px-Levi%27s_Stadium_in_February_2016_prior_to_Super_Bowl_50_%2824398261729%29.jpg' WHERE stadium_id = 50;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/SoFi_Stadium_2023.jpg/330px-SoFi_Stadium_2023.jpg'                                                                                                     WHERE stadium_id = 51;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Lincoln_Financial_Field_%28Aerial_view%29.jpg/330px-Lincoln_Financial_Field_%28Aerial_view%29.jpg'                                                     WHERE stadium_id = 52;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Qwest_Field_North.jpg/330px-Qwest_Field_North.jpg'                                                                                                     WHERE stadium_id = 53;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Gillette_Stadium_%28Top_View%29.jpg/330px-Gillette_Stadium_%28Top_View%29.jpg'                                                                         WHERE stadium_id = 54;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Hard_Rock_Stadium_for_Super_Bowl_LIV_%2849606710103%29.jpg/330px-Hard_Rock_Stadium_for_Super_Bowl_LIV_%2849606710103%29.jpg'                           WHERE stadium_id = 55;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/BC_Place_2015_Women%27s_FIFA_World_Cup.jpg/330px-BC_Place_2015_Women%27s_FIFA_World_Cup.jpg'                                                           WHERE stadium_id = 56;
UPDATE "STADIUM" SET logo_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Toronto_BMO_Field_in_2024.jpg/330px-Toronto_BMO_Field_in_2024.jpg'                                                                                     WHERE stadium_id = 57;
