-- v3.33: Chat por liga — tabla LEAGUE_MESSAGE + RLS + Realtime
-- Solo miembros con approval_status = 'approved' pueden leer/escribir.
-- El creador de la liga (LEAGUE.user_id) también tiene acceso completo.
-- Ejecutar en: Dashboard → SQL Editor → New query

-- ── 1. Tabla ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "LEAGUE_MESSAGE" (
  message_id  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  league_id   INT         NOT NULL REFERENCES "LEAGUE"(league_id) ON DELETE CASCADE,
  user_id     INT         NOT NULL REFERENCES "USER"(user_id) ON DELETE SET NULL,
  content     TEXT        NOT NULL CHECK (char_length(TRIM(content)) BETWEEN 1 AND 1000),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_deleted  BOOLEAN     NOT NULL DEFAULT false,
  deleted_at  TIMESTAMPTZ,
  deleted_by  INT         REFERENCES "USER"(user_id)
);

-- Índice para paginación/búsqueda eficiente
CREATE INDEX IF NOT EXISTS idx_league_message_league_created
  ON "LEAGUE_MESSAGE" (league_id, created_at DESC);

-- ── 2. Realtime ───────────────────────────────────────────────────────────────
-- Para que los cambios lleguen via postgres_changes, la tabla necesita:
-- REPLICA IDENTITY FULL (envía la fila completa en UPDATE/DELETE)
ALTER TABLE "LEAGUE_MESSAGE" REPLICA IDENTITY FULL;

-- Agregar a la publicación de Supabase Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE "LEAGUE_MESSAGE";

-- ── 3. RLS ────────────────────────────────────────────────────────────────────
ALTER TABLE "LEAGUE_MESSAGE" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_all_league_message"      ON "LEAGUE_MESSAGE";
DROP POLICY IF EXISTS "member_select_league_message"  ON "LEAGUE_MESSAGE";
DROP POLICY IF EXISTS "member_insert_league_message"  ON "LEAGUE_MESSAGE";

-- Admin: acceso total
CREATE POLICY "admin_all_league_message" ON "LEAGUE_MESSAGE"
  FOR ALL TO authenticated
  USING     (has_permission('league:admin'))
  WITH CHECK(has_permission('league:admin'));

-- SELECT: miembro aprobado O creador de la liga
CREATE POLICY "member_select_league_message" ON "LEAGUE_MESSAGE"
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM "USER_LEAGUE" ul
      WHERE ul.league_id        = "LEAGUE_MESSAGE".league_id
        AND ul.user_id          = get_my_user_id()
        AND ul.is_deleted       = false
        AND ul.approval_status  = 'approved'
    )
    OR EXISTS (
      SELECT 1 FROM "LEAGUE" l
      WHERE l.league_id = "LEAGUE_MESSAGE".league_id
        AND l.user_id   = get_my_user_id()
    )
  );

-- INSERT: solo el propio usuario aprobado puede insertar sus propios mensajes
CREATE POLICY "member_insert_league_message" ON "LEAGUE_MESSAGE"
  FOR INSERT TO authenticated
  WITH CHECK (
    user_id = get_my_user_id()
    AND (
      EXISTS (
        SELECT 1 FROM "USER_LEAGUE" ul
        WHERE ul.league_id        = "LEAGUE_MESSAGE".league_id
          AND ul.user_id          = get_my_user_id()
          AND ul.is_deleted       = false
          AND ul.approval_status  = 'approved'
      )
      OR EXISTS (
        SELECT 1 FROM "LEAGUE" l
        WHERE l.league_id = "LEAGUE_MESSAGE".league_id
          AND l.user_id   = get_my_user_id()
      )
    )
  );

-- ── 4. Verificar ──────────────────────────────────────────────────────────────
SELECT tablename, policyname, cmd
FROM   pg_policies
WHERE  tablename = 'LEAGUE_MESSAGE'
ORDER  BY policyname;
